[package]
name = "ch2_guessgame"
version = "0.1.0"
authors = ["Tamas <tamas.smahajcsikszabo@outlook.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
